FROM public.ecr.aws/lambda/python:3.12

COPY requirements.txt requirements-aws.txt ${LAMBDA_TASK_ROOT}/
RUN pip install -r ${LAMBDA_TASK_ROOT}/requirements.txt \
                -r ${LAMBDA_TASK_ROOT}/requirements-aws.txt \
                --target "${LAMBDA_TASK_ROOT}"

COPY server.py cloud_secrets.py handler_lambda.py ${LAMBDA_TASK_ROOT}/

CMD ["handler_lambda.handler"]
